name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]
    environment: ${{ matrix.environment }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.SA_EMAIL }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Terraform Init
      run: |
        cd environments/${{ matrix.environment }}
        terraform init \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="prefix=terraform/state/${{ matrix.environment }}"
      env:
        GOOGLE_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: environments/${{ matrix.environment }}

    - name: Terraform Plan
      run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -no-color
      working-directory: environments/${{ matrix.environment }}
      env:
        GOOGLE_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -auto-approve
      working-directory: environments/${{ matrix.environment }}
      env:
        GOOGLE_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
